### PR TITLE
Adds radially symmetric aspheric surfaces and a helper method for aspheric lens components

### PR DESCRIPTION
**Pull request by rdgraham**
Typically moulded aspheric lenses are specified by an aspheric surface with a radially symmetric function.
While a general 2D aspheric surface is available, this is not very helpful for modelling these lenses.

This pull request adds a new aspheric lens component type and the necessary surface functions for defining radially-symmetric polynomials. Lenses with either one or two aspheric surfaces are supported. Lenses with a flat brim around the primary surfaces are supported since this is common with moulded aspheres. Lenses can be constructed with the origin point optionally set to the center or either side of a given aspheric surface with a descriptor string.

Apologies for the changes showing up which are just removals of trailing whitespace. My editor has done this on saving. I would suggest a separate commit at some point to remove trailing whitespace from all files for pep8 compliance.

### CODE REVIEW

**Comment by ramezquitao** [comment]
Thanks for the contribution. I apologize for not mergin it sooner, but I have  been very busy. Next week I will check and apply all the PR

**Comment by ramezquitao** [comment]
It seems this Pr depends on #106 . I will merge both PR, but I think the ray coloring should be changed according what we discussed at #106.

**Comment by rdg-netra** [comment]
OK, thanks for merging!
I will go ahead and make another commit with the changes we discussed.

**Comment by rdgraham** [comment]
OK, thanks for merging!
I will go ahead and make another commit with the changes we discussed.

**Pull request merged**
