### PR TITLE
some minor py3 incompatibilities

### PR DESCRIPTION
**Pull request by fariza**

### CODE REVIEW

**Comment by ijpulidos** [comment]
@fariza Not sure if I'm missing something but where is the reduce package import from six.moves used in the changes you made? I don't see it.

**Comment by fariza** [comment]
It is already there. In Python 2 it belongs to the root namespace in 3 it is inside functools (if I remember correctly). 
So I just had to add the import from six for it to start working correctly

**Comment by ijpulidos** [comment]
Not sure why Travis is complaining but builds fine here.

**Comment by fariza** [comment]
It complains about Pep8 problems, we should really make a one shot effort and clean all the code.

**Pull request merged**
