### PR TITLE
Ray draw color

### PR DESCRIPTION
**Pull request by rdgraham**
Sometimes it is necessary to manually set the color which is used to render a ray. For example, it might not be easily visible if the color is determined by the wavelength. Or it may be useful to change the color to distinguish different sources.

This change adds a draw_color parameter to the ray class and ray sources. If specified, the color of the ray(s) when rendered by Plot3D will be overridden. Since matplotlib was already a dependency, I used matplotlib.color for parsing the color definitions.

Apologies for the changes which are the removal of trailing whitespaces. Looks like my editor did that automatically.

### CODE REVIEW

**Comment by ederag** [comment]
Thanks for the contribution !
This would be useful to differentiate between two sources of same wavelength.

The space changes make it difficult to review,
otherwise it seems well done.

Maybe the `draw_color` should take only an RGB tuple,
to avoid pulling a `matplotlib` dependency, especially in such a deep part ?
The user would then use their preferred tool to handle colors (e.g. [`to_rgb(...)`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.to_rgb.html)),
or even just  `draw_color=wavelength2RGB(another_lambda)` which could be nice as well, and works without `matplotlib`.

**Comment by ramezquitao** [comment]
Thanks for the contribution. I apologize for not mergin it sooner, but I have  been very busy. Next week I will check and apply all the PR

**Comment by rdg-netra** [comment]
Matplotlib already accepts RGB tuples and several other color descriptors see [matplotlib color tutorial](https://matplotlib.org/stable/tutorials/colors/colors.html); the to_rgb method mentioned is what is being used currently. So I think this use-case is covered. It is indeed a heavy package but it was already a dependency for the project so didn't see an issue using it.

**Comment by rdgraham** [comment]
Matplotlib already accepts RGB tuples and several other color descriptors see [matplotlib color tutorial](https://matplotlib.org/stable/tutorials/colors/colors.html); the to_rgb method mentioned is what is being used currently. So I think this use-case is covered. It is indeed a heavy package but it was already a dependency for the project so didn't see an issue using it.

**Comment by ederag** [comment]
@rdgraham What you did made perfect sense.
And indeed, `matplotlib` is a standard dependency of the package.

`matplotlib` is used in `plotutils.py`, where it is mandatory of course.
But this is not needed for 3D plotting.

Otherwise, `matplotlib` is only imported in `surface.pyx` directly, and indirectly through `misc.py`
But only [`matplotlib.tri.Triangulation`](https://matplotlib.org/stable/api/tri_api.html) is used,
which could be replaced with [`scipy.spatial.Delaunay`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html)
albeit with some work as their API differ.

[`to_rgb`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.to_rgb.html) is not used in pyoptools yet.


That's why I'd leave open the path to restrict the `matplotlib` dependency to `plotutils.py`,
and give users the choice to use `matplotlib`  or  not (for colors and for plots if they prefer otherwise).

Hopefully that makes sense as well ? Please feel free to argue further as I'm just giving feedback to help a bit.

**Comment by rdgraham** [comment]
If there is particular interest in dropping matplotlib as a dependency then let me know; I could change this to use something else, such as [webcolors](https://webcolors.readthedocs.io/en/1.11.1/#). However, that is adding an additional dependency and my guess is that a lot of users would be already more familiar with the matplotlib color names so I think it is probably the better overall choice.

I would agree that sourcing the Triangulation method from matplotlib doesn't seem like the best choice, even if matplotlib is a dependency. That is a separate issue though.

What I meant by the to_rgb method being used 'currently' is that it is currently in the PR.

**Comment by ederag** [comment]
> I could change this to use something else, such as [webcolors](https://webcolors.readthedocs.io/en/1.11.1/#)

I'd rather not introduce any dependency at all, and continue to use plain `(r, g, b)` tuples of floats in [0, 1].
Users can then use whatever system they like.
```python
from pyoptools import *
Ray(..., wavelength=600, draw_color=(0.0, 1.0, 1.0), ...)
Ray(..., wavelength=600, draw_color=wavelength2RGB(500), ...)  

from matplotlib.colors import to_rgb
Ray(..., wavelength=600, draw_color=to_rgb("cyan"), ...)
```

**Comment by ramezquitao** [comment]
@rdgraham , I have been checking your PR, and I think it is very useful. There is something I don't like: it is mixing the optical objects used for calculation (Ray) with information used for rendering (abstract draw_color that will be used only when drawing the ray), but I have been thinking and I can't find a way to separate them adequately. Right now we have the label attribute, that for the moment is only a string that was intended to identify the ray as it is propagated in the system. What if this label is removed and we add a "extra_attribs" (maybe this is not the most correct name) dictionary, that could carry the label, the draw_color, and anything else we need to carry with the Ray in the future. What do you guys think?
On another matter, I agree with @ederag . I think it is better to leave the color just as an (r, g, b) tuple of floats in [0, 1]. Outside in your program  you can use matplotlib or webcolors or any other. What do you think?

**Comment by rdgraham** [comment]
Hi @ramezquitao. Good to hear from you.

From an architectural point of view I agree that it is better to separate the rendering information from the raytracing. In my first implementation of this I simply changed the rendering method to allow the color of all rays drawn to be overwritten. Since I am working mostly in the infrared spectrum it was quite important if I wanted to be able to see anything! However, I soon found many situations in which I needed to set the color of individual rays. I could not find any simple way of doing that other than attaching the information to the rays.

I agree that it would be better architecturally to group the draw_color with other optional display properties. We might for example want to be able to have dashed lines as well. If the rendering engine is more advanced at some point it might also be able to display the label (perhaps as a mouse-over tooltip?). So I think putting these in a `draw_properties` dict might make sense. I can try and modify the PR perhaps this weekend to work this way.

From the users point of view, I think it might still be better to allow passing in the draw properties as kwargs and then organizing them internally. I think with this sort of project many users will be engineers/data science people not programmers. So it is better to keep the method signatures as user-friendly as possible. Having to instantiate another object or load in a library is an extra point of confusion for this kind of user. That was the main reason why I initially preferred flexible color specification using matplotlib rather than individual tuples. Although I don't have a strong feeling about it and can change to raw tuples in the next PR if that is preferred.

**Comment by ederag** [comment]
> add a "extra_attribs" (maybe this is not the most correct name) dictionary,
> that could carry the label, the draw_color, and anything else we need to carry with the Ray in the future.

That would be flexible. Maybe with a shorter name like `metadata` or `extra`.
But wouldn't a dict slow things down a lot, as currently all attributes are "copied" in child rays ?

An `Extra` class holding these would be faster and allow the `ray.extra.draw_color` syntax.
The indirection would hopefully be compiled out, but I know little about cython, so this would have to be checked.
Not sure it is worth the extra complexity though.

A way to separate drawing from rays would be to put `label`, `draw_color` and the start ray 
in a python class (e.g. named `Origin`).
But then it would be impossible to color differently a particular child, which seems nice for debugging purposes.

A completely different stance:
store that information in the system, with `ray_add(..., draw_color=...)`, rather than in the rays.
It would need a lookup table, which is not as nice (slower, harder to keep in sync),
but propagation would still be super fast,
drawing stuff would be well separated,
a specific ray color could be changed between the propagate and drawing phases,
and the mechanism would be easily extensible.

**Comment by ederag** [comment]
@rdgraham I saw your message only after posting, and need to read it again tomorrow.

**Comment by ramezquitao** [comment]
@ederag I don't think passing this as a dictionary will slow things down (not too much). when you do something like this:

```
 a={"ww":34,"ee":4}
 b=a
```
both a and b "point" to the same dict. I have to check if the same happens in cython, but I think it does. This means all the rays will have access to the same dict. I'm not sure how this can be handled if we pass the extra arguments as a kwarg as @rdgraham suggest, as it gets unpacked. Maybe in this case things will be slowed down.

I was thinking, and one good thing about this approach is that we can pass the `draw_color` as a string (for example _"red"_), and in the drawing function `matplotlib.colors` or `webcolors` 's  `to_rgb` function can be imported. In this case, the core will still not depend on `matplotlib` nor `webcolor`.

what do guys you think?

**Comment by ederag** [comment]
If only the reference to the dict is copied, then I suppose it should be fast indeed.
But then it would be strange to change the `draw_color` of a ray part
and discover that ancestors and children change color as well.
And so much for debugging (highlight a specific part).

If it is restricted to string, then it is not possible to just link to https://matplotlib.org/stable/tutorials/colors/colors.html,
as the first format shown there is precisely
"RGB or RGBA (red, green, blue, alpha) tuple of float values in a closed interval [0, 1]."
And Plot3D would then depend on `matplotlib`, which is not the case yet.

So it's possible, but there are some drawbacks as well.

**Comment by ramezquitao** [comment]
@ederag  the backing dict can be hidden (private) so no direct change can be made by the user after the Ray is created, and create modify_attrib or even define a  property, so when a change in the dict is requested, it creates a new copy of the dictionary. 
About making Plot3D require matplotlib, I see no problem, as other plotting functions (such as spot_diagram) require matplotlib (well really pylab).

**Pull request merged**
