### PR TITLE
Fix doc build

### PR DESCRIPTION
**Pull request by ederag**
`doc/_build` was currently tracked by git.
Any attempt to build the documentation creates a lot of irrelevant changes in git status,
that hide the relevant changes made.
I guess that the idea was to allow people to get a pre-built documentation,
but that could be done in a separate repository ?

The deletions come from the [necessary cleanup](https://stackoverflow.com/a/36877483/3565696).
The next two commits allow to build and open the documentation with
```bash
cd doc
make html
firefox _build/html/index.html &
```

### CODE REVIEW

**Comment by ramezquitao** [comment]
Applied

**Comment by ederag** [comment]
Thanks for merging. Just so you know, I'm working on other doc updates.

**Comment by ramezquitao** [comment]
Great. Thanks for your help

**Comment by ederag** [comment]
Done (PR #58)

**Pull request merged**
