### PR TITLE
Fix typos in references

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
ping

**Comment by ramezquitao** [comment]
This files are copied from the  https://refractiveindex.info project. This means the corrections are better made there. Still I will merge the pull request, but it is possible it will be lost when we download the latest version of the database.

**Comment by luzpaz** [comment]
@ramezquitao do they have a github repo? Do any of the devs have accounts on github (we could ping them)

**Comment by ederag** [comment]
It looks like the same as last time: https://github.com/cihologramas/pyoptools/pull/101?

**Comment by luzpaz** [comment]
lol full circle. Sorry for the noise.

**Pull request merged**
