### PR TITLE
Fix typos in references

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by ramezquitao** [comment]
I'm not sure we should apply this.  I downloaded the database from https://github.com/polyanskiy/refractiveindex.info-database . Maybe is better to contribute this corrections to the original project? What do you think?

**Comment by luzpaz** [comment]
CC @polyanskiy would that be OK?

**Review by polyanskiy — APPROVED** [review]
Fixes accepted!

**Comment by luzpaz** [comment]
No need for this PR now since fixes were committed upstream. Thanks to all invovled! Closing

**Pull request closed without merging**
